#### PaTE.smk configuration file

# Assemblies must be in data/genomes/{sampleID}.fa
samplesID: ["Podan2", "CBS237.71m", "PaTgp", "PaWa137m", "PaYp", "PcWa139m", "PaWa100p", "PaWa21m", "PaWa28m", "PaWa46p", "PaWa53m", "PaWa58m", "PaWa63p", "PaWa87p"]

## Scripts
renamer: "scripts/renameRMDLconsensi.pl" # Available at https://github.com/genomicrocosm soon

# Minimum size of a contig to get annotated
MINSIZE: 50000 