### PoJellyfish: Producing the distribution of kmers of a given size in *Podospora* genomes
# ===========================================================================
# Sandra Lorena Ament Velasquez
# Johannesson Lab, Evolutionary Biology Center, Uppsala University, Sweden
# 2020/09/21
# ++++++++++++++++++++++++++++++++++++++++++++++

# Samples
SampleIDs: ["Podan2"]

path2assemblies: "path/to/assemblies" # Assume files are called {sample}*.fa*

kmers: ["AGGTAG", "GGGTAG"]

## Scripts
KmerCounts: "scripts/KmerCounts.R"
KmerDist: "scripts/KmerDist.R"