### Circos plot of the Spok blocks
### ----------------------------------
# The Circos configuration files must be in a folder called "circos" in the
# working directory

# A fasta file with all main types of Spok block (representative Psks) from TSD to TSD
allblocks: "data/MainBlocks.fa"

# Samples with gene and TE annotation
samples: ["PaWa137m", "PaWa28m", "PaWa53m", "PaWa58m", "PcWa139m"]
gffs: ["data/PaWa137m.nice.SpokBlock_LA_crew_Slice_5790592_6038100.gff",
       "data/PaWa28m.nice.SpokBlock_LA_crew_Slice_3461167_3622462.gff",
       "data/PaWa53m.nice.SpokBlock_LA_crew_Slice_389477_502882.gff",
       "data/PaWa58m.nice.SpokBlock_LA_crew_Slice_927484_1094941.gff",
       "data/PcWa139m.nice.SpokBlock_LA_Slice_328941_367470.gff"] # Both genes and TEs